- name: Update the apt package index
  become: true
  apt:
    upgrade: yes
    update_cache: yes 

- name: Install require packages
  become: true
  apt:
    name: '{{ item.name }}'
  with_items: '{{ debian_docker_need_packages }}'

- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

- name: Use the following command to set up the stable repository
  shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Update the apt package for docker
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Docker engine
  become: true
  apt:
    name: '{{ item.name }}'
  with_items: '{{ debian_docker_install_packages }}'

- name: User add group
  become: true
  shell: useradd -aG docker kiriake
