homebrew_packages:
  # cui packages
  - { name: ansible }
  - { name: anyenv }
  - { name: awscli }
  - { name: colordiff }
  - { name: cubectx }
  - { name: curl }
  - { name: direnv }
  - { name: docker }
  - { name: gawk }
  - { name: git }
  - { name: ghq }
  - { name: helm }
  - { name: htop }
  - { name: ipcalc }
  - { name: jq }
  - { name: kind }
  - { name: k9s }
  - { name: mas }
  - { name: openssl }
  - { name: peco }
  - { name: rbenv-gemset }
  - { name: reattach-to-user-namespace }
  - { name: stern }
  - { name: tmux }
  - { name: tree }
  - { name: vim }
  - { name: wget }
  - { name: zsh }
  - { name: zsh-completion }
  # gui packages
  - { name: aquaskk }
  - { name: clipy }
  - { name: caffeine }
  - { name: discord }
  - { name: firefox }
  - { name: google-chrome }
  - { name: pycharm }
  - { name: skitch }
  - { name: slack }
  - { name: the-unarchiver }
  - { name: vivaldi }
